### PR TITLE
[pom] Update java-client to 2.3.3

### PR DESCRIPTION
**Pull request by hazendaz**

### CODE REVIEW

**Comment by kazuki43zoo** [comment]
@hazendaz 

2.3.4 has been released already at 05/Oct/16.
see https://issues.couchbase.com/projects/JCBC/versions/13630

**Comment by hazendaz** [comment]
Feel free to bump it forwards.  I was going off versioneye report.  Its usually a couple days behind.

Jeremy

Get Outlook for Androidhttps://aka.ms/ghei36

On Sun, Oct 9, 2016 at 11:33 PM -0400, "Kazuki Shimizu" <notifications@github.com<mailto:notifications@github.com>> wrote:

@hazendazhttps://github.com/hazendaz

2.3.4 has been released already at 05/Oct/16.
see https://issues.couchbase.com/projects/JCBC/versions/13630

##

**Comment by kazuki43zoo** [comment]
@hazendaz, i agree with your opinion 👍

**Comment by hazendaz** [comment]
Didn't realize I didn't merge this when I made the change.  I'm merging now and will update to the next version after ;)

**Pull request merged**
